language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: jeffrey.jagoda@gmail.com
  api_key:
    secure: Dk00dhFzd+Z5ucHv2E9bD//Lluj17CUcT6GymgUzSV9FeJA2kjqQ3MtUZLSFw31zmRSKEh8pzRNGXmWm4Pm84gIrUXLCDWS57vkM54MzRiP8vzjM1pnA2oQdTiZGk1q6aWZ4XlZP19j8MFOWt2eygeWERinqN+uYXYpHYbXZNQE=
  on:
    tags: true
    repo: jagoda/whisp
    branch: master
